version: 2
jobs:
  build:             
    docker:
      - image: public.ecr.aws/q7t9x1p4/platform-build:latest
    steps:      
      - checkout
      - run: aws eks update-kubeconfig --name "${EKS_CLUSTER_NAME}" --region us-west-2
      - run: kubectl get namespaces
workflows:
  version: 2
  build-and-push:
    jobs:
      - build
