version: 2
jobs:
  test:             
    docker:
      - image: klin732/awscli-go
    steps:      
      - checkout
      - run: aws eks update-kubeconfig --name "${EKS_CLUSTER_NAME}" --region us-west-2
      - run: helm version
      - run: kubectl version
      - run: aws --version
      - run: cd helm && eval "${INSTALL_STRING} --dry-run"
  deploy:             
    docker:
      #- image: public.ecr.aws/q7t9x1p4/platform-build:latest
      - image: klin732/awscli-go
    steps:      
      - checkout
      - run: aws eks update-kubeconfig --name "${EKS_CLUSTER_NAME}" --region us-west-2
      - run: cd helm && eval "${INSTALL_STRING}"
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy-approve:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - deploy-approve

